version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  go-112:
    docker:
      - image: circleci/golang:1.12
    working_directory: /home/circleci/go/src/github.com/tksn-jp/go-circleci-test

jobs:
  build:
    executor: go-112
    environment:
      GOPATH: /home/circleci/go
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -v -t -d ./...
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/haya14busa/goverage
      - run: golint ./...
      - run: go vet ./...
      - run: go test -v -race ./...
      - run: goverage -coverprofile=./coverage.txt ./...
      - codecov/upload:
          file: ./coverage.txt
      # - run: bash <(curl -s https://codecov.io/bash)
  # deploy:
  #   environment:
  #     GOPATH: /home/circleci/go
  #   docker:
  #    - image: circleci/golang:1.12
  #   steps:
  #     - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
  #     - checkout
  #     - run: go get -v -t -d ./...
  #     - run: go get github.com/mitchellh/gox
  #     - run: go get github.com/tcnksm/ghr
  #     - run: gox -output "${GOPATH}/pkg/{{.Dir}}_{{.OS}}_{{.Arch}}"  ./ ./...
  #     - run: ghr -u $CIRCLE_PROJECT_USERNAME $CIRCLE_TAG $GOPATH/pkg/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
